ALTER TABLE instance_settings
    ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7) NOT NULL DEFAULT '#3b82f6',
    ADD COLUMN IF NOT EXISTS support_email VARCHAR(254) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS support_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS privacy_policy_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS terms_of_service_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS default_locale VARCHAR(10) NOT NULL DEFAULT 'en';
