root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["web", "--config_path", "./config", "--env", "${ENV:-development}", "--address", "0.0.0.0", "--port", "${APP_PORT:-8081}", "--debug", "${DEBUG:-true}"]
  bin = "${OUTPUT:-./bin/gouno}"
  cmd = "go build -tags ${DB:-postgres} -buildvcs=false -gcflags \"-N -l\" -o ${OUTPUT:-./bin/gouno} ./cmd"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "node_modules", "data", "log", "scripts", "test", "docs",".vscode",".husky",".github", ".githooks", ".codebuddy"]
  exclude_file = ["README.md", "coverage-unit.html", "coverage-unit.out"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
