services:
  # 测试数据库 - MySQL (使用更轻量的 MariaDB Alpine)
  mysql-test:
    image: mariadb:10.11-jammy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gosso_test
      MYSQL_USER: gosso
      MYSQL_PASSWORD: gosso123
    ports:
      - "3308:3306"  # Test 环境端口 (默认端口+2)
    tmpfs:
      - /var/lib/mysql  # 使用内存存储，测试后自动清理
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 10

  # 测试数据库 - PostgreSQL (Alpine 版本)
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gosso_test
      POSTGRES_USER: gosso
      POSTGRES_PASSWORD: gosso123
    ports:
      - "5434:5432"  # Test 环境端口 (默认端口+2)
    tmpfs:
      - /var/lib/postgresql/data  # 使用内存存储
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gosso"]
      timeout: 5s
      retries: 10

  # 邮件测试服务 - Mailpit (Alpine 版本)
  mailpit-test:
    image: axllent/mailpit:latest
    ports:
      - "1027:1025"  # SMTP Test 环境端口 (默认端口+2)
      - "8027:8025"  # Web UI Test 环境端口 (默认端口+2)
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      timeout: 5s
      retries: 5
    
  # Redis 测试服务 (Alpine 版本)
  redis-test:
    image: redis:7-alpine
    ports:
      - "6381:6379"  # Test 环境端口 (默认端口+2)
    tmpfs:
      - /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

networks:
  default:
    name: gosso-test-network