web_server:
    address: 0.0.0.0
    port: 8081
    idle_timeout: 60s
    read_timeout: 5s
    read_header_timeout: 2s
    write_timeout: 30s
    request_timeout: 10s
database:
    driver: pgx
    # dsn: root:123456@tcp(127.0.0.1:3306)/gouno?charset=utf8mb4&parseTime=True&loc=Local
    dsn: host=127.0.0.1 user=postgres password=123456 dbname=gosso port=5432 sslmode=disable TimeZone=Asia/Shanghai search_path=development
    log_level: 2 #日志级别, 1:Silent 2:Error 3:Warn 4:Info
task_pipeline:
    flush_size: 32
    buffer_size: 64
    flush_interval: 1s
